-- 07_finance_accounting.sql

-- 1. Accounting Providers (e.g. UOL)
CREATE TABLE IF NOT EXISTS public.accounting_providers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text NOT NULL, -- 'uol', 'abra', etc.
    name text NOT NULL,
    is_enabled boolean DEFAULT false,
    config jsonb DEFAULT '{}', -- Store API keys, URLs separately or encrypted if possible? For now simple jsonb.
    created_at timestamp with time zone DEFAULT now()
);

-- 2. Accounting Documents (Invoices cached from API)
CREATE TABLE IF NOT EXISTS public.accounting_documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id bigint REFERENCES public.accounting_providers(id),
    external_id text NOT NULL, -- ID from the external system
    type text NOT NULL, -- 'sales_invoice', 'purchase_invoice'
    number text, -- Visible document number
    
    supplier_name text, -- For purchase invoices
    supplier_ico text,
    
    amount numeric, -- Total amount
    currency text DEFAULT 'CZK',
    
    issue_date date,
    due_date date,
    tax_date date,
    
    description text,
    status text, -- 'paid', 'unpaid', etc. from external system
    
    raw_data jsonb, -- Full JSON response from API for future proofing
    
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- Index for faster lookups by external ID
CREATE INDEX IF NOT EXISTS idx_accounting_documents_external_id ON public.accounting_documents(external_id);
CREATE INDEX IF NOT EXISTS idx_accounting_documents_type ON public.accounting_documents(type);

-- 3. Accounting Mappings (Linking documents/costs to internal entities)
CREATE TABLE IF NOT EXISTS public.accounting_mappings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id bigint REFERENCES public.accounting_documents(id) ON DELETE CASCADE,
    
    -- Targets (Polymorphic-ish, or just nullable FKs)
    akce_id bigint REFERENCES public.akce(id),
    pracovnik_id bigint REFERENCES public.pracovnici(id),
    division_id bigint REFERENCES public.divisions(id),
    
    cost_category text, -- 'material', 'service', 'overhead'
    amount numeric NOT NULL, -- How much of the document amount is mapped here
    
    note text,
    created_at timestamp with time zone DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_accounting_mappings_akce_id ON public.accounting_mappings(akce_id);

-- 4. Sync Logs
CREATE TABLE IF NOT EXISTS public.accounting_sync_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id bigint REFERENCES public.accounting_providers(id),
    started_at timestamp with time zone DEFAULT now(),
    ended_at timestamp with time zone,
    status text, -- 'running', 'success', 'error'
    records_processed integer DEFAULT 0,
    error_message text
);
