-- Create accounting_journal table for caching General Ledger entries
create table if not exists accounting_journal (
  id bigint generated by default as identity primary key,
  uol_id text not null unique, -- External ID from UOL
  date date not null,
  account_md text not null, -- Debit side (Má dáti)
  account_d text not null,  -- Credit side (Dal)
  amount numeric not null,
  currency text not null default 'CZK',
  text text,                -- Description
  fiscal_year integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Indexes for reporting performance
create index if not exists accounting_journal_date_idx on accounting_journal (date);
create index if not exists accounting_journal_account_md_idx on accounting_journal (account_md);
create index if not exists accounting_journal_account_d_idx on accounting_journal (account_d);
create index if not exists accounting_journal_fiscal_year_idx on accounting_journal (fiscal_year);

-- Enable RLS
alter table accounting_journal enable row level security;

-- Policies (assuming usage by authenticated users/admins)
create policy "Enable read access for authenticated users"
on accounting_journal for select
to authenticated
using (true);

create policy "Enable all access for service role"
on accounting_journal for all
to service_role
using (true);
