-- Create table for storing cached bank movements
create table if not exists accounting_bank_movements (
    id bigint generated by default as identity primary key,
    bank_account_id text not null, -- ID of the account in UOL
    movement_id text not null, -- Unique ID from UOL
    date date not null,
    amount numeric(15, 2) not null,
    currency text not null default 'CZK',
    variable_symbol text,
    description text,
    raw_data jsonb, -- Store full JSON response for future reference
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    
    constraint accounting_bank_movements_movement_id_key unique (movement_id)
);

-- Index for searching and summing
create index if not exists accounting_bank_movements_bank_account_id_idx on accounting_bank_movements (bank_account_id);
create index if not exists accounting_bank_movements_date_idx on accounting_bank_movements (date);

-- RLS Policies
alter table accounting_bank_movements enable row level security;

create policy "Users can view bank movements"
    on accounting_bank_movements for select
    to authenticated
    using (true); -- Or restrict based on permissions if needed

create policy "Service role can manage bank movements"
    on accounting_bank_movements for all
    to service_role
    using (true)
    with check (true);
