-- Create accounting_accounts table for Chart of Accounts
create table if not exists accounting_accounts (
  id bigint generated by default as identity primary key,
  code text not null unique, -- Account number (e.g., '311')
  name text not null,        -- Account name (e.g., 'Odběratelé')
  type text,                 -- Optional: 'asset', 'liability', 'expense', 'revenue'
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Index for fast lookup by code
create index if not exists accounting_accounts_code_idx on accounting_accounts (code);

-- Enable RLS
alter table accounting_accounts enable row level security;

-- Policies
create policy "Enable read access for authenticated users"
on accounting_accounts for select
to authenticated
using (true);

create policy "Enable all access for service role"
on accounting_accounts for all
to service_role
using (true);

-- Seed Standard Czech Chart of Accounts (Basic Set)
insert into accounting_accounts (code, name, type) values
-- Class 0: Long-term Assets
('013', 'Software', 'asset'),
('021', 'Stavby', 'asset'),
('022', 'Samostatné hmotné movité věci a soubory movitých věcí', 'asset'),
('081', 'Oprávky ke stavbám', 'asset'), -- Contra-asset (usually credit balance)
('082', 'Oprávky k sam. hmot. movitým věcem', 'asset'),

-- Class 1: Inventory
('111', 'Pořízení materiálu', 'asset'),
('112', 'Materiál na skladě', 'asset'),
('132', 'Zboží na skladě a v prodejnách', 'asset'),

-- Class 2: Financial Accounts
('211', 'Pokladna', 'asset'),
('213', 'Ceniny', 'asset'),
('221', 'Bankovní účty', 'asset'),
('261', 'Peníze na cestě', 'asset'),

-- Class 3: Relations (Receivables/Payables)
('311', 'Odběratelé', 'asset'),
('314', 'Poskytnuté provozní zálohy', 'asset'),
('315', 'Ostatní pohledávky', 'asset'),
('321', 'Dodavatelé', 'liability'),
('324', 'Přijaté provozní zálohy', 'liability'),
('325', 'Ostatní závazky', 'liability'),
('331', 'Zaměstnanci', 'liability'),
('336', 'Zúčtování s institucemi soc. a zdrav. pojištění', 'liability'),
('341', 'Daň z příjmů', 'liability'),
('342', 'Ostatní přímé daně', 'liability'),
('343', 'Daň z přidané hodnoty', 'liability'), -- Mixed
('345', 'Ostatní daně a poplatky', 'liability'),
('379', 'Jiné závazky', 'liability'),
('395', 'Vnitřní zúčtování', 'liability'),

-- Class 4: Equity & Long-term Liabilities
('411', 'Základní kapitál', 'liability'),
('421', 'Rezervní fond', 'liability'),
('428', 'Nerozdělený zisk minulých let', 'liability'),
('429', 'Neuhrazená ztráta minulých let', 'liability'),
('431', 'Výsledek hospodaření ve schvalovacím řízení', 'liability'),
('451', 'Dlouhodobé bankovní úvěry', 'liability'),

-- Class 5: Costs
('501', 'Spotřeba materiálu', 'expense'),
('502', 'Spotřeba energie', 'expense'),
('504', 'Prodané zboží', 'expense'),
('511', 'Opravy a udržování', 'expense'),
('512', 'Cestovné', 'expense'),
('513', 'Náklady na reprezentaci', 'expense'),
('518', 'Ostatní služby', 'expense'),
('521', 'Mzdové náklady', 'expense'),
('524', 'Zákonné sociální a zdravotní pojištění', 'expense'),
('538', 'Ostatní daně a poplatky', 'expense'),
('546', 'Odpis pohledávky', 'expense'),
('562', 'Úroky', 'expense'),
('563', 'Kurzové ztráty', 'expense'),
('568', 'Ostatní finanční náklady', 'expense'),
('591', 'Daň z příjmů - splatná', 'expense'),

-- Class 6: Revenues
('602', 'Tržby z prodeje služeb', 'revenue'),
('604', 'Tržby za zboží', 'revenue'),
('648', 'Ostatní provozní výnosy', 'revenue'),
('662', 'Úroky', 'revenue'),
('663', 'Kurzové zisky', 'revenue')
on conflict (code) do nothing;
