-- Comprehensive Czech Chart of Accounts (Účtová osnova pro podnikatele)
-- Covers Class 0-6 for standard business needs

insert into accounting_accounts (code, name, type) values
-- Class 0: Dlouhodobý majetek
('012', 'Nehmotné výsledky vývoje', 'asset'),
('013', 'Software', 'asset'),
('014', 'Ostatní ocenitelná práva', 'asset'),
('015', 'Goodwill', 'asset'),
('019', 'Ostatní dlouhodobý nehmotný majetek', 'asset'),
('021', 'Stavby', 'asset'),
('022', 'Samostatné hmotné movité věci a soubory movitých věcí', 'asset'),
('025', 'Pěstitelské celky trvalých porostů', 'asset'),
('026', 'Dospělá zvířata a jejich skupiny', 'asset'),
('029', 'Jiný dlouhodobý hmotný majetek', 'asset'),
('031', 'Pozemky', 'asset'),
('032', 'Umělecká díla a sbírky', 'asset'),
('041', 'Nedokončený dlouhodobý nehmotný majetek', 'asset'),
('042', 'Nedokončený dlouhodobý hmotný majetek', 'asset'),
('043', 'Nedokončený dlouhodobý finanční majetek', 'asset'),
('051', 'Poskytnuté zálohy na dlouhodobý nehmotný majetek', 'asset'),
('052', 'Poskytnuté zálohy na dlouhodobý hmotný majetek', 'asset'),
('053', 'Poskytnuté zálohy na dlouhodobý finanční majetek', 'asset'),
('061', 'Podíly - ovládaná nebo ovládající osoba', 'asset'),
('062', 'Podíly - podstatný vliv', 'asset'),
('063', 'Ostatní dlouhodobé cenné papíry a podíly', 'asset'),
('065', 'Dluhové cenné papíry držené do splatnosti', 'asset'),
('066', 'Zápůjčky a úvěry - ovládaná nebo ovládající osoba', 'asset'),
('067', 'Zápůjčky a úvěry - podstatný vliv', 'asset'),
('068', 'Ostatní dlouhodobé zápůjčky a úvěry', 'asset'),
('069', 'Jiný dlouhodobý finanční majetek', 'asset'),
('072', 'Oprávky k nehmotným výsledkům vývoje', 'asset'), -- contra
('073', 'Oprávky k softwaru', 'asset'), -- contra
('074', 'Oprávky k ostatním ocenitelným právům', 'asset'), -- contra
('075', 'Oprávky ke goodwillu', 'asset'), -- contra
('079', 'Oprávky k jinému dlouhodobému nehmotnému majetku', 'asset'), -- contra
('081', 'Oprávky ke stavbám', 'asset'), -- contra
('082', 'Oprávky k sam. hmot. movitým věcem a souborům', 'asset'), -- contra
('085', 'Oprávky k pěstitelským celkům trvalých porostů', 'asset'), -- contra
('086', 'Oprávky k dospělým zvířatům', 'asset'), -- contra
('089', 'Oprávky k jinému dlouhodobému hmotnému majetku', 'asset'), -- contra
('091', 'Opravná položka k dlouhodobému nehmotnému majetku', 'asset'), -- contra
('092', 'Opravná položka k dlouhodobému hmotnému majetku', 'asset'), -- contra
('093', 'Opravná položka k dlouhodobému nehmotnému majetku', 'asset'), -- contra
('094', 'Opravná položka k nedokončenému dlouhodobému nehmotnému majetku', 'asset'), -- contra
('095', 'Opravná položka k poskytnutým zálohám na dlouhodobý majetek', 'asset'), -- contra
('096', 'Opravná položka k dlouhodobému finančnímu majetku', 'asset'), -- contra

-- Class 1: Zásoby
('111', 'Pořízení materiálu', 'asset'),
('112', 'Materiál na skladě', 'asset'),
('119', 'Materiál na cestě', 'asset'),
('121', 'Nedokončená výroba', 'asset'),
('122', 'Polotovary vlastní výroby', 'asset'),
('123', 'Výrobky', 'asset'),
('124', 'Mladá a ostatní zvířata', 'asset'),
('131', 'Pořízení zboží', 'asset'),
('132', 'Zboží na skladě a v prodejnách', 'asset'),
('139', 'Zboží na cestě', 'asset'),
('151', 'Poskytnuté zálohy na zásoby - materiál', 'asset'),
('152', 'Poskytnuté zálohy na zásoby - zvířata', 'asset'),
('153', 'Poskytnuté zálohy na zásoby - zboží', 'asset'),
('191', 'Opravná položka k materiálu', 'asset'), -- contra
('192', 'Opravná položka k nedokončené výrobě', 'asset'), -- contra
('193', 'Opravná položka k polotovarům vlastní výroby', 'asset'), -- contra
('194', 'Opravná položka k výrobkům', 'asset'), -- contra
('195', 'Opravná položka ke zvířatům', 'asset'), -- contra
('196', 'Opravná položka ke zboží', 'asset'), -- contra
('197', 'Opravná položka k zálohám na zásoby', 'asset'), -- contra

-- Class 2: Finanční účty
('211', 'Pokladna', 'asset'),
('213', 'Ceniny', 'asset'),
('221', 'Bankovní účty', 'asset'),
('231', 'Krátkodobé bankovní úvěry', 'liability'),
('232', 'Eskontní úvěry', 'liability'),
('241', 'Vydané krátkodobé dluhopisy', 'liability'),
('251', 'Majetkové cenné papíry k obchodování', 'asset'),
('252', 'Vlastní akcie a vlastní obchodní podíly', 'asset'),
('253', 'Dluhové cenné papíry k obchodování', 'asset'),
('255', 'Vlastní dluhopisy', 'asset'),
('256', 'Dluhové cenné papíry se splatností do 1 roku držené do splatnosti', 'asset'),
('257', 'Ostatní cenné papíry k obchodování', 'asset'),
('259', 'Pořizování krátkodobého finančního majetku', 'asset'),
('261', 'Peníze na cestě', 'asset'),
('291', 'Opravná položka ke krátkodobému finančnímu majetku', 'asset'), -- contra

-- Class 3: Zúčtovací vztahy
('311', 'Odběratelé', 'asset'),
('312', 'Směnky k inkasu', 'asset'),
('313', 'Pohledávky za eskontované cenné papíry', 'asset'),
('314', 'Poskytnuté provozní zálohy - dlouhodobé a krátkodobé', 'asset'),
('315', 'Ostatní pohledávky', 'asset'),
('321', 'Dodavatelé', 'liability'),
('322', 'Směnky k úhradě', 'liability'),
('324', 'Přijaté provozní zálohy', 'liability'),
('325', 'Ostatní závazky', 'liability'),
('331', 'Zaměstnanci', 'liability'),
('333', 'Jiné závazky vůči zaměstnancům', 'liability'),
('335', 'Pohledávky za zaměstnanci', 'asset'),
('336', 'Zúčtování s institucemi soc. a zdrav. pojištění', 'liability'),
('341', 'Daň z příjmů', 'liability'),
('342', 'Ostatní přímé daně', 'liability'),
('343', 'Daň z přidané hodnoty', 'liability'),
('345', 'Ostatní daně a poplatky', 'liability'),
('346', 'Dotace ze státního rozpočtu', 'liability'),
('347', 'Ostatní dotace', 'liability'),
('349', 'Vyrovnávací účet pro DPH', 'liability'),
('351', 'Pohledávky - ovládaná nebo ovládající osoba', 'asset'),
('352', 'Pohledávky - podstatný vliv', 'asset'),
('353', 'Pohledávky za společníky', 'asset'),
('354', 'Pohledávky ze správy', 'asset'),
('355', 'Ostatní pohledávky za společníky', 'asset'),
('358', 'Pohledávky k účastníkům sdružení', 'asset'),
('361', 'Závazky - ovládaná nebo ovládající osoba', 'liability'),
('362', 'Závazky - podstatný vliv', 'liability'),
('364', 'Závazky ke společníkům při úhradě ztráty', 'liability'),
('365', 'Ostatní závazky ke společníkům', 'liability'),
('366', 'Závazky ke společníkům ze závislé činnosti', 'liability'),
('367', 'Závazky z upsaných nesplacených cenných papírů a vkladů', 'liability'),
('368', 'Závazky k účastníkům sdružení', 'liability'),
('371', 'Pohledávky z prodeje podniku', 'asset'),
('372', 'Závazky z prodeje podniku', 'liability'),
('373', 'Pohledávky a závazky z pevných termínových operací', 'asset'),
('374', 'Pohledávky z nájmu', 'asset'),
('375', 'Pohledávky z emitovaných dluhopisů', 'asset'),
('376', 'Nakoupené opce', 'asset'),
('377', 'Prodané opce', 'liability'),
('378', 'Jiné pohledávky', 'asset'),
('379', 'Jiné závazky', 'liability'),
('381', 'Náklady příštích období', 'asset'),
('382', 'Komplexní náklady příštích období', 'asset'),
('383', 'Výdaje příštích období', 'liability'),
('384', 'Výnosy příštích období', 'liability'),
('385', 'Příjmy příštích období', 'asset'),
('388', 'Dohadné účty aktivní', 'asset'),
('389', 'Dohadné účty pasivní', 'liability'),
('391', 'Opravná položka k pohledávkám', 'asset'), -- contra
('395', 'Vnitřní zúčtování', 'liability'),
('398', 'Spojovací účet při sdružení', 'liability'),

-- Class 4: Kapitálové účty a dlouhodobé závazky
('411', 'Základní kapitál', 'liability'),
('413', 'Kapitálové fondy', 'liability'),
('414', 'Oceňovací rozdíly z přecenění majetku a závazků', 'liability'),
('419', 'Změny základního kapitálu', 'liability'),
('421', 'Rezervní fond', 'liability'),
('422', 'Nedělitelný fond', 'liability'),
('423', 'Statutární fondy', 'liability'),
('424', 'Ostatní fondy', 'liability'),
('427', 'Oceňovací rozdíly z přecenění při přeměnách', 'liability'),
('428', 'Nerozdělený zisk minulých let', 'liability'),
('429', 'Neuhrazená ztráta minulých let', 'liability'),
('431', 'Výsledek hospodaření ve schvalovacím řízení', 'liability'),
('451', 'Dlouhodobé bankovní úvěry', 'liability'),
('455', 'Dlouhodobé závazky k úvěrovým institucím', 'liability'),
('459', 'Ostatní dlouhodobé závazky', 'liability'),
('461', 'Bankovní úvěry', 'liability'),
('471', 'Dlouhodobé závazky - ovládaná nebo ovládající osoba', 'liability'),
('472', 'Dlouhodobé závazky - podstatný vliv', 'liability'),
('473', 'Vydané dluhopisy', 'liability'),
('474', 'Závazky z pronájmu', 'liability'),
('475', 'Dlouhodobé přijaté zálohy', 'liability'),
('478', 'Dlouhodobé směnky k úhradě', 'liability'),
('479', 'Jiné dlouhodobé závazky', 'liability'),
('481', 'Odložený daňový závazek a pohledávka', 'liability'),

-- Class 5: Náklady
('501', 'Spotřeba materiálu', 'expense'),
('502', 'Spotřeba energie', 'expense'),
('503', 'Spotřeba ostatních neskladovatelných dodávek', 'expense'),
('504', 'Prodané zboží', 'expense'),
('511', 'Opravy a udržování', 'expense'),
('512', 'Cestovné', 'expense'),
('513', 'Náklady na reprezentaci', 'expense'),
('518', 'Ostatní služby', 'expense'),
('521', 'Mzdové náklady', 'expense'),
('522', 'Příjmy společníků a členů družstva ze závislé činnosti', 'expense'),
('523', 'Odměny členům orgánů společnosti a družstva', 'expense'),
('524', 'Zákonné sociální a zdravotní pojištění', 'expense'),
('525', 'Ostatní sociální pojištění', 'expense'),
('526', 'Sociální náklady individuálního podnikatele', 'expense'),
('527', 'Zákonné sociální náklady', 'expense'),
('528', 'Ostatní sociální náklady', 'expense'),
('531', 'Daň silniční', 'expense'),
('532', 'Daň z nemovitých věcí', 'expense'),
('538', 'Ostatní daně a poplatky', 'expense'),
('541', 'Zůstatková cena prodaného dlouhodobého nehmotného a hmotného majetku', 'expense'),
('542', 'Prodaný materiál', 'expense'),
('543', 'Dary', 'expense'),
('544', 'Smluvní pokuty a úroky z prodlení', 'expense'),
('545', 'Ostatní pokuty a penále', 'expense'),
('546', 'Odpis pohledávky', 'expense'),
('548', 'Ostatní provozní náklady', 'expense'),
('549', 'Manka a škody z provozní činnosti', 'expense'),
('551', 'Odpisy dlouhodobého nehmotného a hmotného majetku', 'expense'),
('552', 'Tvorba a zúčtování rezerv', 'expense'),
('554', 'Tvorba a zúčtování opravných položek', 'expense'),
('555', 'Tvorba a zúčtování komplexních nákladů příštích období', 'expense'),
('557', 'Zúčtování oprávky k opravné položce (aktivní)', 'expense'),
('558', 'Tvorba a zúčtování zákonných opravných položek v provozní činnosti', 'expense'),
('559', 'Tvorba a zúčtování opravných položek v provozní činnosti', 'expense'),
('561', 'Prodané cenné papíry a podíly', 'expense'),
('562', 'Úroky', 'expense'),
('563', 'Kurzové ztráty', 'expense'),
('564', 'Náklady z přecenění cenných papírů', 'expense'),
('565', 'Ostatní finanční náklady', 'expense'),
('566', 'Náklady z finančního majetku', 'expense'),
('567', 'Náklady z derivátových operací', 'expense'),
('568', 'Ostatní finanční náklady', 'expense'),
('569', 'Manka a škody na finančním majetku', 'expense'),
('574', 'Tvorba a zúčtování finančních rezerv', 'expense'),
('579', 'Tvorba a zúčtování opravných položek ve finanční činnosti', 'expense'),
('582', 'Aktivace vnitropodnikových služeb', 'expense'), -- Usually negative expense (Revenue side logic sometimes) or contra-expense
('585', 'Aktivace materiálu a zboží', 'expense'),
('586', 'Aktivace vnitropodnikových zásob', 'expense'),
('587', 'Aktivace dlouhodobého nehmotného majetku', 'expense'),
('588', 'Aktivace dlouhodobého hmotného majetku', 'expense'),
('591', 'Daň z příjmů - splatná', 'expense'),
('592', 'Daň z příjmů - odložená', 'expense'),
('595', 'Dodatečné odvody daně z příjmů', 'expense'),
('597', 'Převod podílu na výsledku hospodaření společníkům', 'expense'),

-- Class 6: Výnosy
('601', 'Tržby za vlastní výrobky', 'revenue'),
('602', 'Tržby z prodeje služeb', 'revenue'),
('604', 'Tržby za zboží', 'revenue'),
('641', 'Tržby z prodeje dlouhodobého nehmotného a hmotného majetku', 'revenue'),
('642', 'Tržby z prodeje materiálu', 'revenue'),
('644', 'Smluvní pokuty a úroky z prodlení', 'revenue'),
('646', 'Výnosy z odepsaných pohledávek', 'revenue'),
('648', 'Ostatní provozní výnosy', 'revenue'),
('655', 'Výnosy z dlouhodobého finančního majetku', 'revenue'),
('657', 'Výnosy z derivátových operací', 'revenue'),
('661', 'Tržby z prodeje cenných papírů a podílů', 'revenue'),
('662', 'Úroky', 'revenue'),
('663', 'Kurzové zisky', 'revenue'),
('664', 'Výnosy z přecenění cenných papírů', 'revenue'),
('665', 'Výnosy z dlouhodobého finančního majetku', 'revenue'),
('666', 'Výnosy z krátkodobého finančního majetku', 'revenue'),
('668', 'Ostatní finanční výnosy', 'revenue'),
('697', 'Převod provozního výsledku hospodaření', 'revenue'),
('698', 'Převod finančního výsledku hospodaření', 'revenue')

on conflict (code) do nothing;
