-- Create suppliers table
create table public.suppliers (
  id bigint generated by default as identity not null primary key,
  name text not null,
  type text not null check (type in ('sftp_xml', 'sftp_csv', 'api_rest', 'sftp_demos')),
  config jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  last_sync_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

-- Create supplier_items table
create table public.supplier_items (
  id bigint generated by default as identity not null primary key,
  supplier_id bigint not null references public.suppliers(id) on delete cascade,
  code text not null,
  name text not null,
  description text,
  price numeric not null,
  currency text not null default 'CZK',
  unit text,
  image_url text,
  category text,
  metadata jsonb default '{}'::jsonb,
  updated_at timestamp with time zone not null default now(),
  unique(supplier_id, code)
);

-- Add indexes
create index idx_supplier_items_supplier_id on public.supplier_items(supplier_id);
create index idx_supplier_items_code on public.supplier_items(code);
create index idx_supplier_items_name_search on public.supplier_items using gin (to_tsvector('simple', name));
