-- Create Offer Items Table
CREATE TABLE IF NOT EXISTS polozky_nabidky (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nabidka_id BIGINT REFERENCES nabidky(id) ON DELETE CASCADE,
  nazev TEXT NOT NULL,
  typ TEXT CHECK (typ IN ('skrinka', 'spotrebic', 'sluzba', 'ostatni')),
  mnozstvi NUMERIC DEFAULT 1,
  cena_ks NUMERIC DEFAULT 0,
  celkem NUMERIC GENERATED ALWAYS AS (mnozstvi * cena_ks) STORED,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for performance
CREATE INDEX idx_polozky_nabidky_nabidka_id ON polozky_nabidky(nabidka_id);

-- Verify
SELECT * FROM polozky_nabidky LIMIT 1;
