-- Vytvoří tabulku "akce" pro záznam projektů/akcí
CREATE TABLE IF NOT EXISTS public.akce (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nazev text NOT NULL,
  datum date NOT NULL,
  klient_id bigint NULL,
  cena_klient numeric(12,2) NOT NULL DEFAULT 0,
  material_klient numeric(12,2) NOT NULL DEFAULT 0,
  material_my numeric(12,2) NOT NULL DEFAULT 0,
  odhad_hodin numeric(10,2) NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- FK na tabulku klienti (upravit název tabulky pokud se liší)
ALTER TABLE public.akce
  ADD CONSTRAINT akce_klient_fk FOREIGN KEY (klient_id)
    REFERENCES public.klienti(id)
    ON DELETE SET NULL
    ON UPDATE CASCADE;

-- Indexy pro rychlé filtrování podle data a klienta
CREATE INDEX IF NOT EXISTS idx_akce_datum ON public.akce (datum);
CREATE INDEX IF NOT EXISTS idx_akce_klient ON public.akce (klient_id);

-- Poznámka: pokud používáte Row Level Security (RLS), přidejte politiky pro INSERT/SELECT/UPDATE/DELETE podle rolí.
