CREATE TABLE mzdy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pracovnik_id BIGINT REFERENCES pracovnici(id) ON DELETE SET NULL,
    mesic INTEGER NOT NULL,
    rok INTEGER NOT NULL,
    hruba_mzda NUMERIC,
    faktura NUMERIC,
    priplatek NUMERIC,
    celkova_castka NUMERIC GENERATED ALWAYS AS (COALESCE(hruba_mzda, 0) + COALESCE(faktura, 0) + COALESCE(priplatek, 0)) STORED,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(pracovnik_id, mesic, rok)
);
