-- Vytvoří tabulku "platby" pro ukládání plateb dodavatelům / rekonciliace
CREATE TABLE IF NOT EXISTS public.platby (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dodavatel_id bigint NOT NULL,
  mesic date NOT NULL, -- uložíme první den měsíce, např. '2025-11-01'
  hodiny numeric(10,2) NOT NULL DEFAULT 0,
  sazba numeric(10,2) NOT NULL DEFAULT 0,
  castka numeric(12,2) NOT NULL DEFAULT 0,
  zaplaceno boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT platby_dodavatel_mesic_unique UNIQUE (dodavatel_id, mesic)
);

-- FK na tabulku pracovnici (upravit název/tabulku pokud se liší)
ALTER TABLE public.platby
  ADD CONSTRAINT platby_dodavatel_fk FOREIGN KEY (dodavatel_id)
    REFERENCES public.pracovnici(id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE;

-- Indexy pro rychlé filtrování podle měsíce a dodavatele
CREATE INDEX IF NOT EXISTS idx_platby_mesic ON public.platby (mesic);
CREATE INDEX IF NOT EXISTS idx_platby_dodavatel ON public.platby (dodavatel_id);

-- Poznámka: pokud používáte Row Level Security (RLS), upravte politiky tak, aby INSERT/SELECT/DELETE byly povoleny pro potřebné role.
