-- 1. Create Types Table
CREATE TABLE IF NOT EXISTS polozky_typy (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nazev TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Seed Defaults (Idempotent)
INSERT INTO polozky_typy (nazev) VALUES 
('Skříňka'), ('Spotřebič'), ('Služba'), ('Ostatní')
ON CONFLICT (nazev) DO NOTHING;

-- 3. Enable RLS
ALTER TABLE polozky_typy ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON polozky_typy FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON polozky_typy FOR INSERT WITH CHECK (true);

-- 4. Remove Constraint from Items Table
-- We try to guess the constraint name. Usually it is table_column_check.
-- We must make sure we don't fail if it doesn't exist.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'polozky_nabidky_typ_check') THEN
    ALTER TABLE polozky_nabidky DROP CONSTRAINT polozky_nabidky_typ_check;
  END IF;
END $$;

-- 5. Force Refresh
NOTIFY pgrst, 'reload schema';
