-- 1. Create Inventory Centers Table
drop table if exists public.inventory_centers cascade;
drop table if exists public.inventory_stock cascade;

create table public.inventory_centers (
  id bigint generated by default as identity primary key,
  name text not null,
  color text default '#64748b', -- Slate-500 default
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for centers
alter table public.inventory_centers enable row level security;
create policy "Centers are viewable by everyone" on public.inventory_centers for select using (true);
create policy "Centers are insertable by authenticated users" on public.inventory_centers for insert with check (auth.role() = 'authenticated');
create policy "Centers are updatable by authenticated users" on public.inventory_centers for update using (auth.role() = 'authenticated');
create policy "Centers are deletable by authenticated users" on public.inventory_centers for delete using (auth.role() = 'authenticated');

-- 2. Create Default Center
insert into public.inventory_centers (name, color) values ('Hlavní sklad', '#E30613');

-- 3. Create Inventory Stock Table (Stock per Center)
create table if not exists public.inventory_stock (
  id bigint generated by default as identity primary key,
  inventory_item_id bigint references public.inventory_items(id) on delete cascade not null,
  center_id bigint references public.inventory_centers(id) on delete cascade not null,
  quantity numeric not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(inventory_item_id, center_id)
);

-- RLS for stock
alter table public.inventory_stock enable row level security;
create policy "Stock is viewable by everyone" on public.inventory_stock for select using (true);
create policy "Stock is insertable by authenticated users" on public.inventory_stock for insert with check (auth.role() = 'authenticated');
create policy "Stock is updatable by authenticated users" on public.inventory_stock for update using (auth.role() = 'authenticated');

-- 4. Migrate Existing Stock to Default Center
do $$
declare
  default_center_id bigint;
begin
  select id into default_center_id from public.inventory_centers where name = 'Hlavní sklad' limit 1;
  
  -- Insert existing items into stock table
  insert into public.inventory_stock (inventory_item_id, center_id, quantity)
  select id, default_center_id, quantity
  from public.inventory_items;

end $$;

-- 5. Update Inventory Movements
alter table public.inventory_movements add column if not exists center_id bigint references public.inventory_centers(id);
alter table public.inventory_movements add column if not exists target_center_id bigint references public.inventory_centers(id); -- For transfers

-- Update existing movements to point to default center
do $$
declare
  default_center_id bigint;
begin
  select id into default_center_id from public.inventory_centers where name = 'Hlavní sklad' limit 1;
  
  update public.inventory_movements
  set center_id = default_center_id
  where center_id is null;
end $$;

alter table public.inventory_movements alter column center_id set not null;

-- 6. Trigger to Maintain Total Quantity on Inventory Items
-- Function to calculate total
create or replace function public.update_inventory_item_total()
returns trigger as $$
begin
  update public.inventory_items
  set quantity = (
    select coalesce(sum(quantity), 0)
    from public.inventory_stock
    where inventory_item_id = coalesce(new.inventory_item_id, old.inventory_item_id)
  )
  where id = coalesce(new.inventory_item_id, old.inventory_item_id);
  return null;
end;
$$ language plpgsql;

-- Trigger
drop trigger if exists on_stock_change on public.inventory_stock;
create trigger on_stock_change
after insert or update or delete on public.inventory_stock
for each row execute function public.update_inventory_item_total();

-- 7. Add Transfer Type Constraint Check (if applicable, though movement types are likely text)
-- Our schema uses text for 'type', so 'TRANSFER' is valid.
