-- 1. Create Statuses Table
CREATE TABLE IF NOT EXISTS nabidky_stavy (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nazev TEXT NOT NULL,
  color TEXT,
  poradi INT DEFAULT 0
);

-- 2. Insert Default Statuses
INSERT INTO nabidky_stavy (nazev, color, poradi) VALUES
('Rozpracováno', 'gray', 10),
('Odesláno', 'blue', 20),
('Akceptováno', 'green', 30),
('Odmítnuto', 'red', 40),
('Storno', 'gray', 50);

-- 3. Add Foreign Key Column to Offers
ALTER TABLE nabidky ADD COLUMN IF NOT EXISTS stav_id BIGINT REFERENCES nabidky_stavy(id);

-- 4. Migrate Existing Data
UPDATE nabidky SET stav_id = (SELECT id FROM nabidky_stavy WHERE nazev = 'Rozpracováno') WHERE stav = 'rozpracováno';
UPDATE nabidky SET stav_id = (SELECT id FROM nabidky_stavy WHERE nazev = 'Odesláno') WHERE stav = 'odesláno';
UPDATE nabidky SET stav_id = (SELECT id FROM nabidky_stavy WHERE nazev = 'Akceptováno') WHERE stav = 'schváleno';
UPDATE nabidky SET stav_id = (SELECT id FROM nabidky_stavy WHERE nazev = 'Odmítnuto') WHERE stav = 'zamítnuto';

-- 5. Set default for any missing/new
UPDATE nabidky SET stav_id = (SELECT id FROM nabidky_stavy WHERE nazev = 'Rozpracováno') WHERE stav_id IS NULL;

-- 6. Verify
SELECT n.id, n.nazev, s.nazev as stav_nazev FROM nabidky n JOIN nabidky_stavy s ON n.stav_id = s.id LIMIT 5;
