export interface NabidkaStav {
    id: number;
    nazev: string;
    color: string;
    poradi: number;
}

export interface Nabidka {
    id: number;
    cislo?: string;
    nazev: string;
    klient_id?: number | null;
    akce_id?: number | null;
    poznamka?: string;
    description?: string; // Legacy field match
    platnost_do?: string; // New: Validity date
    stav_id?: number | null;
    celkova_cena: number;
    sleva_procenta?: number;
    created_at: string;
    updated_at: string;
    klienti?: {
        id: number;
        nazev: string;
        kontaktni_osoba?: string | null;
        telefon?: string | null;
        email?: string | null;
        address?: string | null;
        web?: string | null;
        ico?: string | null;
        dic?: string | null;
    } | null;
    akce?: {
        id: number;
        nazev: string;
    } | null;
    uvodni_text?: string;
    division_id?: number | null;
    divisions?: {
        id: number;
        nazev: string;
    } | null;
    nabidky_stavy?: NabidkaStav | null;
    zobrazeni_klienta?: string | null;
    zobrazeni_klienta_pole?: string[] | null;
}

export interface NabidkaPolozka {
    id: number;
    nabidka_id: number;
    nazev: string;
    typ: string; // Dynamic type
    popis?: string; // New: Description
    obrazek_url?: string; // New: Image URL
    mnozstvi: number;
    cena_ks: number;
    sazba_dph?: number; // New: VAT Rate (0, 12, 21)
    celkem: number;
    poradi?: number;
    je_sleva?: boolean;
}

/** Payload for creating a new offer item (celkem is generated by DB) */
export type CreateOfferItemPayload = {
    nabidka_id: number;
    nazev: string;
    typ: string;
    mnozstvi: number;
    cena_ks: number;
    popis?: string | null;
    sazba_dph?: number;
    obrazek_url?: string | null;
    je_sleva?: boolean;
};

/** Payload for updating an existing offer item (celkem is generated by DB) */
export type UpdateOfferItemPayload = Partial<Omit<CreateOfferItemPayload, 'nabidka_id'>>;

/** Payload for creating an action from offer acceptance */
export interface CreateActionPayload {
    nazev: string;
    klient_id?: number | null;
    cena_klient?: number;
    odhad_hodin?: number;
    material_klient?: number;
    material_my?: number;
}

/** Row shape returned by getActions */
export interface AkceRow {
    id: number;
    nazev: string;
    klient_id: number | null;
}

/** Row shape returned by getDivisionsList */
export interface DivisionRow {
    id: number;
    nazev: string;
}
